### ISSUE TITLE
Theme causes ArcMenu to be misaligned

### ISSUE THREAD

**Issue by werdahias** [Fausto-Korpsvart/Gruvbox-GTK-Theme#1]
Hi, I really like you theme. I'm running Debian 42 and GNOME Shell 42. I also you the ArcMenu shell extension. When I run the theme, the menu misalignes. This is not an ArcMenu bug. When I switch the shell theme to vanilla, it works as intented.
![Screenshot 1](https://user-images.githubusercontent.com/23419969/161895769-b3e2230b-5f0c-4f7a-b4f1-8e29b00112a5.png)
![Screenshot 2](https://user-images.githubusercontent.com/23419969/161895773-660e7a6c-d4fb-4542-b648-176462d6bca1.png)

**Comment by Fausto-Korpsvart** [comment]
> 

Thank you for reporting, @CountOmega, when I have a bit of time I will look for the solution, I hope and I would appreciate a bit of patience.

**Comment by CountOmega** [comment]
Same with latest version and bl theme

**Comment by Fausto-Korpsvart** [comment]
> Same with latest version and bl theme

Thanks for reporting, I guess with the new changes in Gnome Shell something must have happened to make Arc Menu misaligned. 
In the meantime, you can tweak the Arc Menu settings a bit, I remember there is an option to control the margins and position.
