### ISSUE TITLE
[Feature request] Custom theme for Gnome TextEditor

### ISSUE THREAD

**Issue by CountOmega** [Fausto-Korpsvart/Gruvbox-GTK-Theme#11]
I saw you already made a css theme for gedit. I use the "new" [Text Editor](https://apps.gnome.org/app/org.gnome.TextEditor/) most of the time because it has syntax highlighting and a few other nice features over gedit. It already has a few predefined themes, these are located under `/usr/share/gnome-text-editor/styles`. I'd appreciate if you could make a custom one with the Gruvbox color scheme for it.

**Comment by Fausto-Korpsvart** [comment]
> I saw you already made a css theme for gedit. I use the "new" [Text Editor](https://apps.gnome.org/app/org.gnome.TextEditor/) most of the time because it has syntax highlighting and a few other nice features over gedit. It already has a few predefined themes, these are located under `/usr/share/gnome-text-editor/styles`. I'd appreciate if you could make a custom one with the Gruvbox color scheme for it.

Actually the theme for Gedit works with the new Gnome editor, I did a test when Gnome 42 was still in beta and the new editor was making its first appearances, just place the file in the path: `/usr/share/gnome-text-editor/styles` and then they appear in the selection of predefined themes, could you check if they still work? If not, I could start working on new themes to make them work in the new editor.

**Comment by CountOmega** [comment]
Work like a charm, thanks! Maybe mention it in the README that it works
