### ISSUE TITLE
Brave web browser GTK+ issue

### ISSUE THREAD

**Issue by ghost** [Fausto-Korpsvart/Gruvbox-GTK-Theme#15]
I'm using Xfce and my browser looks like this (2nd image with compositor disabled to show the problem more clearly). Not sure what the problem is but I am coming from the Kanagawa theme where I've had no issues. Sorry if this is the wrong place to post and thanks for any help.

![Screenshot_2022-09-29_19-04-51](https://user-images.githubusercontent.com/97992750/193136136-a78d826e-ebdf-43e7-81a8-d30370e663b4.png)
![Screenshot_2022-09-29_21-25-56](https://user-images.githubusercontent.com/97992750/193136146-5c2d8f8c-81d1-46d1-b8c1-cb172f75584e.png)

**Comment by Fausto-Korpsvart** [comment]
> 
Wow, that looks pretty bad, it's weird because I always do tests before I publish the themes

Thanks for reporting it, I'm working on updates this week, and I'm going to check this problem, as I'll update some themes next week.

Again, thanks for reporting it, and thanks for your support.

**Comment by aditamaputra3** [comment]
i have same problem with chromium based browser and i try to edit gtk-3.0/gtk-dark.css and gtk.css at line chromium. give the box-shadow : none; 
![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/53744105/1ee9cf0f-5923-4680-8c4a-5916b7424585)

**Comment by Fausto-Korpsvart** [comment]
> i have same problem with chromium based browser and i try to edit gtk-3.0/gtk-dark.css and gtk.css at line chromium. give the box-shadow : none; ![image](https://user-images.githubusercontent.com/53744105/239691458-1ee9cf0f-5923-4680-8c4a-5916b7424585.png)

I thought this was already fixed, thanks for reporting it, it will be fixed in the next update.
