### ISSUE TITLE
wrong alignment with Dock

### ISSUE THREAD

**Issue by coodyme** [Fausto-Korpsvart/Gruvbox-GTK-Theme#18]
It's possible to fix the Dock content (icons) alignment to the center?

![image](https://user-images.githubusercontent.com/7965922/197750124-a1696c51-cac8-4d50-a25f-6d759350f77a.png)

**Comment by Fausto-Korpsvart** [comment]
Yes, this is a problem with Ubuntu Dock, I disabled the Ubuntu Dock and installed the Dash to Dock extension, this solves the problem, at least until I solve this issue.
Thanks for reporting it.

**Comment by lily-ginger** [comment]
Just wanted to leave the note to future people that dash to dock is broken on ubuntu 22.04 (the dock disappears and freezes the system if you open application view). So that solution doesn't work anymore :)
