### ISSUE TITLE
Gnome Quick Settings colors

### ISSUE THREAD

**Issue by johanhammar** [Fausto-Korpsvart/Gruvbox-GTK-Theme#19]
The Quick Settings colors in Gnome 43 is a bit off.  See the attached screenshot

![2022-11-02_13-51](https://user-images.githubusercontent.com/69011/199496145-b57e7861-d1c3-4988-bbfb-28ae1f6436a3.png)

Details:

Ubuntu 22.10
Gnome 43

Let me know if you need anything from me.

**Comment by Fausto-Korpsvart** [comment]
> The Quick Settings colors in Gnome 43 is a bit off. See the attached screenshot
> 
> ![2022-11-02_13-51](https://user-images.githubusercontent.com/69011/199496145-b57e7861-d1c3-4988-bbfb-28ae1f6436a3.png)
> 
> Details:
> 
> Ubuntu 22.10 Gnome 43
> 
> Let me know if you need anything from me.

Yes, this is because I haven't adapted the theme for the new version of Gnome Shell yet, as soon as I can, I'll make an update.

**Comment by johanhammar** [comment]
Looks great now! Thanks
