### ISSUE TITLE
Unusually Tall Header Bar on Libadwaita apps.

### ISSUE THREAD

**Issue by ScribeAwoken** [Fausto-Korpsvart/Gruvbox-GTK-Theme#2]
So I've found that this theme (and presumably your others, though I have yet to test them) seems to break the headerbar items in Libadwaita apps. More specifically, it makes any widgets in the headerbars for these apps unusually tall.

Note that I'm able to theme these apps by putting the gtk.css file for GTK4 in `~/.config/gtk-4.0`. I have yet to see if it has the same effect with non-libadwaita GTK4 apps. I also had to make a few other tweaks in order for Libadwaita apps to properly follow the color scheme. My only changes were just a few color definitions based on [this template from the GNOME gitlab](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/_defaults.scss)

This does seem to be an upstream issue, since this shows up in the Graphite theme, so I don't know if this is something you would want to fix yourself, or if you would want to wait for an upstream fix that you could implement in your themes. I have already [opened an issue](https://github.com/vinceliuice/Graphite-gtk-theme/issues/56) on the Graphite theme, so it might be a good idea to keep an eye on that as well.

I've also attached three screenshots below demonstrating the issue across your theme and the original Graphite theme, and the properly-sized header bar that the apps use while using Libadwaita.

![image](https://user-images.githubusercontent.com/96320530/163289031-666c4688-b8a3-41e5-ae71-586e485111c7.png)

![image](https://user-images.githubusercontent.com/96320530/163289274-64840a66-b1d2-4465-b5aa-aad42999c95d.png)

![image](https://user-images.githubusercontent.com/96320530/163289285-bcc5460e-80dd-4a53-abe1-b97ec5ddcabd.png)

**Comment by Fausto-Korpsvart** [comment]
> So I've found that this theme (and presumably your others, though I have yet to test them) seems to break the headerbar items in Libadwaita apps. More specifically, it makes any widgets in the headerbars for these apps unusually tall.
> 
> Note that I'm able to theme these apps by putting the gtk.css file for GTK4 in `~/.config/gtk-4.0`. I have yet to see if it has the same effect with non-libadwaita GTK4 apps. I also had to make a few other tweaks in order for Libadwaita apps to properly follow the color scheme. My only changes were just a few color definitions based on [this template from the GNOME gitlab](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/stylesheet/_defaults.scss)
> 
> This does seem to be an upstream issue, since this shows up in the Graphite theme, so I don't know if this is something you would want to fix yourself, or if you would want to wait for an upstream fix that you could implement in your themes. I have already [opened an issue](https://github.com/vinceliuice/Graphite-gtk-theme/issues/56) on the Graphite theme, so it might be a good idea to keep an eye on that as well.
> 
> I've also attached three screenshots below demonstrating the issue across your theme and the original Graphite theme, and the properly-sized header bar that the apps use while using Libadwaita.
> 
> ![image](https://user-images.githubusercontent.com/96320530/163289031-666c4688-b8a3-41e5-ae71-586e485111c7.png)
> 
> ![image](https://user-images.githubusercontent.com/96320530/163289274-64840a66-b1d2-4465-b5aa-aad42999c95d.png)
> 
> ![image](https://user-images.githubusercontent.com/96320530/163289285-bcc5460e-80dd-4a53-abe1-b97ec5ddcabd.png)

Greetings, @ScribeAwoken.

And yes, as expected, the change to Gnome 42 was going to bring a lot of problems with themes, but with the release, as far as I understand, not everything has been ported to 'libadwaita', I guess this will be gradual and that in future versions the complete change will be made.

I don't know what version of Fedora you are using, I have done my tests with Fedora-36, and I know that it is no longer possible to apply themes from '.themes' and that the new path is '.config/gtk.4.0/gtk.css', but in my tests I haven't had that problem, I should have a look again.
With regard to the operation in non 'libadwaita' applications, the theme works normally, my tests have been with the theme 'Tokyonight', I have put the theme 'libadwaita' in its respective directory and the other themes in '.themes' and it has worked very well the integration to maintain a uniform theme between applications that are and that are not 'libadwaita'.
But, you see, I don't know much about creating GTK themes, but I'm looking for a way to learn more about 'libadwaita' so I can make them work in these new versions of GNOME, I hope you have a little patience while I do some research and learn a bit, I guess many developers are doing the same to find a way to bring back theme customization to GNOME. 

Thanks for reporting, it's very helpful.

These are some screenshots of my tests with the 'Tokyonight' theme, the tests are on GnomeOS and Fedora36, as you can see there are still some small bugs that I hope to fix.

![tokyonight-gnome42](https://user-images.githubusercontent.com/47998118/163409288-e8843183-7790-4749-89b2-1ec0c55c1fb0.png)

**Comment by ScribeAwoken** [comment]
I'm also using the Fedora 36 beta.

If you are unable to replicate the issue, then I might try a few things on my end to see if I can find a fix for things. I'll report back with my findings

**Comment by ScribeAwoken** [comment]
Update: I'm having this issue regardless of style sheet, so I don't think this is an issue with the theme

**Comment by Fausto-Korpsvart** [comment]
> 
That might explain why I can't reproduce the error, I've been trying, but I can't get it. 
Anyway I'm working on fixing the little bugs I have in Tokyonight, so I can adapt it to Grubvox, I've also used the Gnome style template in Gitlab to make some changes, but maybe I don't know enough to make the changes without errors happening xD, anyway I'm learning, and I hope to fix them soon to be able to upload a stable theme.

Anyway, thanks for reporting the bugs };-]

**Comment by ScribeAwoken** [comment]
No problem

Though I did find something that... might actually point things in the right direction

so I spun up a Fedora Silverblue VM and upgraded it from Fedora Silverblue 35 to Fedora Silverblue 36, and it seems like it's *specifically* Extensions Manager that has this issue...

except I see in your screenshot that it looks perfectly fine (though I see that you also use the normal Adwaita switch widget rather than the custom one)

part of me wonders if that may explain something here

**Comment by ScribeAwoken** [comment]
Okay scratch what I just said. the new GNOME text editor also has the thick top bar.

that said I'm tinkering with the theme a bit to see if I can find the culprit. I think I'm getting there.
