### ISSUE TITLE
Not working in GNOME 43

### ISSUE THREAD

**Issue by D3vil0p3r** [Fausto-Korpsvart/Gruvbox-GTK-Theme#20]
Hello,
I always used this wonderful theme, but now that I upgraded GNOME to 43, it is not working anymore:

![image](https://user-images.githubusercontent.com/83867734/199967001-cdd91e96-89c7-412a-83f4-04176fd0b0a3.png)

Is there the chance to make it compatible with GNOME 43?

**Comment by Fausto-Korpsvart** [comment]
> Hello, I always used this wonderful theme, but now that I upgraded GNOME to 43, it is not working anymore:
> 
> ![image](https://user-images.githubusercontent.com/83867734/199967001-cdd91e96-89c7-412a-83f4-04176fd0b0a3.png)
> 
> Is there the chance to make it compatible with GNOME 43?
I know, these days I'm working on adapting the themes for Gnome 43, next week I hope to be able to update most of them.
Thanks for reporting.

**Comment by D3vil0p3r** [comment]
Thank you for the answer @Fausto-Korpsvart Now what I did in my GNOME 43 is:
* Downloading the `Gruvbox-Dark-B.zip` and `Gruvbox-Dark-B-G42.zip`
* Extracting the first one in `/usr/share/themes` and the second one in the current directory and I get `Gruvbox-Dark-B.css`
* `cp -rf Gruvbox-Dark-B.css /usr/share/themes/Gruvbox-Dark-B/gtk-4.0/gtk.css`
* Run the following commands:
  ```
  mkdir -p "${HOME}/.config/gtk-4.0"
  ln -sf "/usr/share/themes/Gruvbox-Dark-B/gtk-4.0/assets" "${HOME}/.config/gtk-4.0/assets"
  ln -sf "/usr/share/themes/Gruvbox-Dark-B/gtk-4.0/gtk.css" "${HOME}/.config/gtk-4.0/gtk.css"
  ln -sf "/usr/share/themes/Gruvbox-Dark-B/gtk-4.0/gtk-dark.css" "${HOME}/.config/gtk-4.0/gtk-dark.css"
  ```
And the theme now is working also on my GNOME 43.

In your updates of your themes you will theme also things like:
![image](https://user-images.githubusercontent.com/83867734/200036939-cf972ff4-5a3a-4416-95df-f4072cac2cc2.png)

?

**Comment by Fausto-Korpsvart** [comment]
> Thank you for the answer @Fausto-Korpsvart Now what I did in my GNOME 43 is:
> 
> * Downloading the `Gruvbox-Dark-B.zip` and `Gruvbox-Dark-B-G42.zip`
> * Extracting the first one in `/usr/share/themes` and the second one in the current directory and I get `Gruvbox-Dark-B.css`
> * `cp -rf Gruvbox-Dark-B.css /usr/share/themes/Gruvbox-Dark-B/gtk-4.0/gtk.css`
> * Run the following commands:
>   ```
>   mkdir -p "${HOME}/.config/gtk-4.0"
>   ln -sf "/usr/share/themes/Gruvbox-Dark-B/gtk-4.0/assets" "${HOME}/.config/gtk-4.0/assets"
>   ln -sf "/usr/share/themes/Gruvbox-Dark-B/gtk-4.0/gtk.css" "${HOME}/.config/gtk-4.0/gtk.css"
>   ln -sf "/usr/share/themes/Gruvbox-Dark-B/gtk-4.0/gtk-dark.css" "${HOME}/.config/gtk-4.0/gtk-dark.css"
>   ```
> 
> And the theme now is working also on my GNOME 43.
> 
> In your updates of your themes you will theme also things like: ![image](https://user-images.githubusercontent.com/83867734/200036939-cf972ff4-5a3a-4416-95df-f4072cac2cc2.png)
> 
> ?

Yes, you can perfectly do that, the problem is that in the GTK4 files that you put in the `~/.themes` directory, many styles are not applied very well, some Title Bars are very tall or some buttons have a lot of padding, so the G42 file only overwrites the styles needed to fit the Gruvbox theme and leaving the rest of the default styles for the Libdawaita theme, pretty much what I'm trying to do is color and add only the styles needed, though I guess over time more apps will come to Libadwaita and the style sheets will have to be migrated to `~/config/gtk-4.0` which will make the style sheet bigger.

This is what Nautilus will look like ported to Gnome 43, only this is the Tokyonight version theme without borders.
![nautilus](https://user-images.githubusercontent.com/47998118/200040864-ef09411e-98bc-4a48-a519-26d5f5d96664.png)

And this is what Gnome Shell will look like adapted to Gnome 43.
![shell](https://user-images.githubusercontent.com/47998118/200040868-cf67fa18-b1c7-4034-9d5d-fd0c93b591e2.png)

This is obviously the Tokyonight theme, but it will be adapted for Gruvbox as well.

**Comment by D3vil0p3r** [comment]
@Fausto-Korpsvart your work for GNOME 43 is wonderful!!! Thank you! I hope to see available theme as soon as possible!

**Comment by Fausto-Korpsvart** [comment]
> @Fausto-Korpsvart your work for GNOME 43 is wonderful!!! Thank you! I hope to see available theme as soon as possible!

Thanks for your support, I hope to start updating some themes next week, I'll try to start with Tokyonight and Gruvbox.
Thanks again for your support }:-]

**Comment by Fausto-Korpsvart** [comment]
> @Fausto-Korpsvart your work for GNOME 43 is wonderful!!! Thank you! I hope to see available theme as soon as possible!

@D3vil0p3r, The Tokyonight theme is ready and you can check it out now to get an idea of how it will look adapted for Gruvbox.

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r, The Tokyonight theme is ready and you can check it out now to get an idea of how it will look adapted for Gruvbox.

I think it works very well! The result on my system is the following:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83867734/202582054-1f49e7bb-fd1d-433d-8df6-ca9b4be6fa95.png">

**Comment by D3vil0p3r** [comment]
> > @Fausto-Korpsvart your work for GNOME 43 is wonderful!!! Thank you! I hope to see available theme as soon as possible!
> 
> @D3vil0p3r, The Tokyonight theme is ready and you can check it out now to get an idea of how it will look adapted for Gruvbox.

Hello mate! Is there some news about Gruvbox theme?

**Comment by megascrapper** [comment]
> > > @Fausto-Korpsvart your work for GNOME 43 is wonderful!!! Thank you! I hope to see available theme as soon as possible!
> > 
> > 
> > @D3vil0p3r, The Tokyonight theme is ready and you can check it out now to get an idea of how it will look adapted for Gruvbox.
> 
> Hello mate! Is there some news about Gruvbox theme?

It's already out now. Just head over to the [pling page](https://www.pling.com/p/1681313/).

**Comment by D3vil0p3r** [comment]
> It's already out now. Just head over to the [pling page](https://www.pling.com/p/1681313/).

Thank you mate. I confirm it works correctly.

@Fausto-Korpsvart I wish to make you a request: on Internet there are no updated themes based on red-colors. The ones that can be found online are too old and not maintained anymore.
I appreciate a lot your taste and I would like you to ask if you can create a deep red-based theme for GNOME. For example one that was followed but not maintained anymore is https://github.com/rtlewis88/rtl88-Themes/tree/Abyss-Desktop-Theme-Icons-and-Folders:
![image](https://user-images.githubusercontent.com/83867734/205455270-821cc5b9-e014-4595-bce9-2431d997f56d.png)

In your opinion is possible to create a GTK theme starting from this (that is not maintained anymore) with your wonderful taste?

**Comment by bluedudexoo** [comment]
Just curious, has the Gnome Shell portion for this been finished? My GTK4 apps are themed correctly, but it seems like the notification bar/quick settings from the top bar are still blue.
