### ISSUE TITLE
Wrong colors in Gruvbox-Dark-BL-LB 0.10

### ISSUE THREAD

**Issue by johanhammar** [Fausto-Korpsvart/Gruvbox-GTK-Theme#22]
Hi!

Some colors seems to have been mixed up with other themes like the Tokyo-Night-theme in commit https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/commit/492292eb178a751762f434f2c3b6b893b9710b95

I.e. 

#0db9d7 in https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/blob/master/themes/Gruvbox-Dark-BL-LB/gnome-shell/gnome-shell.css

Before

![Screenshot from 2022-11-24 20-33-59](https://user-images.githubusercontent.com/69011/203854805-27effe15-9288-429a-97c4-6a537d08f3e9.png)

After

![Screenshot from 2022-11-24 20-34-16](https://user-images.githubusercontent.com/69011/203854816-e9a235ed-2ef6-43e9-b7ad-8936fdb51c17.png)

Thanks for a great theme :+1:

**Comment by Fausto-Korpsvart** [comment]
> 

Yes, I've already prepared the update to make the change, actually it was my mistake to place the Gnome Shell Legacy Buttons themes from Tokyonight inside the Gruvbox themes, but I've already changed the themes and made some fixes and improvements, I hope to make the update in a few hours.

**Comment by Fausto-Korpsvart** [comment]
> Hi!
> 
> Some colors seems to have been mixed up with other themes like the Tokyo-Night-theme in commit [492292e](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/commit/492292eb178a751762f434f2c3b6b893b9710b95)
> 
> I.e.
> 
> #0db9d7 in https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/blob/master/themes/Gruvbox-Dark-BL-LB/gnome-shell/gnome-shell.css
> 
> Before
> 
> ![Screenshot from 2022-11-24 20-33-59](https://user-images.githubusercontent.com/69011/203854805-27effe15-9288-429a-97c4-6a537d08f3e9.png)
> 
> After
> 
> ![Screenshot from 2022-11-24 20-34-16](https://user-images.githubusercontent.com/69011/203854816-e9a235ed-2ef6-43e9-b7ad-8936fdb51c17.png)
> 
> Thanks for a great theme +1

Theme Updated, thanks for your support. }:]

**Comment by johanhammar** [comment]
Looks great! Thanks
