### ISSUE TITLE
shutdown dialog window looks all broken

### ISSUE THREAD

**Issue by Jeffrey-de-Bruijn** [Fausto-Korpsvart/Gruvbox-GTK-Theme#3]
![Screenshot from 2022-05-16 23-21-16](https://user-images.githubusercontent.com/101387642/168684657-cf5e7ff9-e0b5-46d3-b09b-6fcb015b1e04.png)
Screenshot contains all the info, GNOME Shell 3.32.2 on VzLinux 8.5

**Comment by Fausto-Korpsvart** [comment]
> ![Screenshot from 2022-05-16 23-21-16](https://user-images.githubusercontent.com/101387642/168684657-cf5e7ff9-e0b5-46d3-b09b-6fcb015b1e04.png) Screenshot contains all the info, GNOME Shell 3.32.2 on VzLinux 8.5

Hi,  thanks for reporting, I will soon make an update that fixes many bugs.

**Comment by Jeffrey-de-Bruijn** [comment]
> I will soon make an update that fixes many bugs.

Glad to hear that. I have contrast issues with text in some applications such as Evolution, do these fixes include fixes to such issues?

If you give me an email address I can share with you a screenshot.

**Comment by Fausto-Korpsvart** [comment]
> > I will soon make an update that fixes many bugs.
> 
> Glad to hear that. I have contrast issues with text in some applications such as Evolution, do these fixes include fixes to such issues?
> 
> If you give me an email address I can share with you a screenshot.

Sorry, I don't use the 'Evolution' mail client, but I will check to see what you mean, anyway, I would like you to post some screenshots, so I know specifically the contrast error you have seen and, if you don't mind, you could post the screenshots here, so others can have some reference in case they have the same error as you; again thanks for your support and for reporting the errors to fix them.
