### ISSUE TITLE
wrong buttons for xfwm4 (not legacy instead theme is marked as LB)

### ISSUE THREAD

**Issue by the-saddest-clown** [Fausto-Korpsvart/Gruvbox-GTK-Theme#30]
All the Gruvbox dark LB (Legacy Buttons) themes don't have legacy buttons for wfxm4.
![Capture d’écran_2023-01-25_03-19-22](https://user-images.githubusercontent.com/83234199/214466042-3093ff7f-833b-4c62-915b-eb3c53561656.png)

**Comment by Fausto-Korpsvart** [comment]
> All the Gruvbox dark LB (Legacy Buttons) themes don't have legacy buttons for wfxm4. ![Capture d’écran_2023-01-25_03-19-22](https://user-images.githubusercontent.com/83234199/214466042-3093ff7f-833b-4c62-915b-eb3c53561656.png)

I will review, correct and update soon.
Thank you for reporting.
