### ISSUE TITLE
Selecting text doesn't highlight

### ISSUE THREAD

**Issue by Noob-linux-user** [Fausto-Korpsvart/Gruvbox-GTK-Theme#31]
While using certain websites or apps like Geary, while selecting text the highlighting color doesn't show up. It actually does but since the highlighting color is almost white, it's very hard to distinguish what I have selected and what I haven't.
I am using Linux mint 20.3 Cinnamon

**Comment by Fausto-Korpsvart** [comment]
> While using certain websites or apps like Geary, while selecting text the highlighting color doesn't show up. It actually does but since the highlighting color is almost white, it's very hard to distinguish what I have selected and what I haven't. I am using Linux mint 20.3 Cinnamon

Could you show some screenshots? I would like to see the error.

Anyway, I'm checking for bugs and possible errors in the themes to update soon. 

As always, thanks for reporting }:]
