### ISSUE TITLE
Text in Gnome-Shell of Gruvbox-Dark-BL-LB is unreadable 

### ISSUE THREAD

**Issue by Raxelgrande** [Fausto-Korpsvart/Gruvbox-GTK-Theme#32]
![Captura desde 2023-02-19 12-47-33](https://user-images.githubusercontent.com/93939943/219965742-8f6f53c3-e0d0-42d9-b7e1-0d87a75ab763.png)
As you can see, the volume/brightness icons are black on a black background (changing icon themes doesn't affect the result). The notifications area is also affected (using quick settings tweaker, that also doesn't affect the result)
Im using the latest version Ubuntu 22.10 offers right now, 43.1

**Comment by Fausto-Korpsvart** [comment]
> ![Captura desde 2023-02-19 12-47-33](https://user-images.githubusercontent.com/93939943/219965742-8f6f53c3-e0d0-42d9-b7e1-0d87a75ab763.png) As you can see, the volume/brightness icons are black on a black background (changing icon themes doesn't affect the result). The notifications area is also affected (using quick settings tweaker, that also doesn't affect the result) Im using the latest version Ubuntu 22.10 offers right now, 43.1

Thanks for reporting, I will soon resume the GTK themes project and I will fix this bug.
Thanks for your support.
