### ISSUE TITLE
Overview search text color

### ISSUE THREAD

**Issue by doxxedd** [Fausto-Korpsvart/Gruvbox-GTK-Theme#36]
![Screenshot from 2023-03-27 16-34-49](https://user-images.githubusercontent.com/94665539/228060319-489ca69b-dc11-4060-829f-7ee2428805a3.png)

Could we possibly change the red and orange text color from the search result to either the yellow accent color or complete white? If not, could you please tell me where I can make this change.

**Comment by Fausto-Korpsvart** [comment]
> ![Screenshot from 2023-03-27 16-34-49](https://user-images.githubusercontent.com/94665539/228060319-489ca69b-dc11-4060-829f-7ee2428805a3.png)
> 
> Could we possibly change the red and orange text color from the search result to either the yellow accent color or complete white? If not, could you please tell me where I can make this change.

Greetings.
Sorry for the delay.

I didn't really take into account that many use the `Blur my Shell` extension, in the next update I will leave the default values, which is white.

Thanks for reporting and for the support.
