### ISSUE TITLE
Issues in Gnome Shell (Gnome 44)

### ISSUE THREAD

**Issue by dawetmaster** [Fausto-Korpsvart/Gruvbox-GTK-Theme#37]
This theme is working in Gnome 44, but it has bugs on Quick Settings (located in top right). On VPN and Wireless, for example, the dropdown button is located at the right outside the main button, not inside as intended.

**Comment by Fausto-Korpsvart** [comment]
> This theme is working in Gnome 44, but it has bugs on Quick Settings (located in top right). On VPN and Wireless, for example, the dropdown button is located at the right outside the main button, not inside as intended.

Thanks for reporting.

I hope to have some time soon to fix bugs and update every theme, work doesn't leave me much time for now, so when I have a moment I'll dedicate myself to fixing bugs and update.

Thanks for your support.

**Comment by masakk1** [comment]
I can second this! It's very annoying. I switch my networks a lot and it's very painful to accidentally hit the "power saver mode".
There isn't much else that isn't working though, just the quick settings.

I'll provide some screenshots to show the problem

**Comment by Fausto-Korpsvart** [comment]
> I can second this! It's very annoying. I switch my networks a lot and it's very painful to accidentally hit the "power saver mode". There isn't much else that isn't working though, just the quick settings.
> 
> I'll provide some screenshots to show the problem
> 
> ![image](https://user-images.githubusercontent.com/105455722/235461014-7c710fd6-2da7-4baf-84ec-5858c657bf10.png)

I know, I know the bug is annoying, and I'm sorry for having the project a bit abandoned, but my work and studies don't leave me much time at the moment, in my free time I'm trying to solve some problems and when everything is ready I'll make an update.

Thanks for reporting.

**Comment by joe733** [comment]
@Fausto-Korpsvart, if you're okay, I can help with a bit of maintenance during my off time.

**Comment by chirag-ghosh** [comment]
Well I tried fixing it. Please have a look :)

**Comment by Fausto-Korpsvart** [comment]
> Well I tried fixing it. Please have a look :)

I updated `Tokyonight` this day, and started working on the `Gruvbox Dark Border` theme, to update tomorrow.

This is a screenshot showing the progress, I'm still not quite convinced about the `Quick Settings` colours, maybe when I update it will change a bit, but this is what I have so far, now I just have to work on the borderless theme.
![gruvbox-dark](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/47998118/267d1e17-dd76-4e54-88d8-195e4447a008)
![grubox-dark-2](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/47998118/fa083548-8ebe-4f11-9450-15030fce427c)

**Comment by chirag-ghosh** [comment]
Looks great. Waiting for the update.

**Comment by Fausto-Korpsvart** [comment]
Updated.
Please check and report if some errors persists }:-]

**Comment by acepukas** [comment]
Hey, just tried the update out and my computer went to 100% utilization on all CPU cores as soon as I dropped the theme folder into `~/.themes`. At first I couldn't figure out what was happening. Tried to select default theme but couldn't launch any apps, let alone gnome-tweaks. Disabled extensions from command line and the cores were still going full throttle. The only thing that got things calmed down was removing the theme folder (which has a spelling mistake by the way `Grubvox-Dark-BL`) from `~/.themes`.

Is something in the css maybe causing that? I don't know enough about gnome css to troubleshoot.

**Comment by joe733** [comment]
Hi, any idea why @masakk1 control plane look different than mine?

`@masakk1`'s

![masakk1](https://user-images.githubusercontent.com/105455722/235461014-7c710fd6-2da7-4baf-84ec-5858c657bf10.png)

`mine`

![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/38415384/f3903a47-4398-41ea-8d7a-4305dad5dd71)

**Comment by masakk1** [comment]
@joe733 it kinda glitched cuz I had plugins and disabled them.... How come yours has a way different look, are you using the theme?

Also it's a desktop not a laptop

**Comment by Fausto-Korpsvart** [comment]
> Hi, any idea why @masakk1 control plane look different than mine?
> 
> `@masakk1`'s
> 
> ![masakk1](https://user-images.githubusercontent.com/105455722/235461014-7c710fd6-2da7-4baf-84ec-5858c657bf10.png)
> 
> `mine`
> 
> ![image](https://user-images.githubusercontent.com/38415384/240502311-f3903a47-4398-41ea-8d7a-4305dad5dd71.png)
> 
> The colors, why is is deep blue, instead of yellowish?
> 
> ```
> $ gsettings get org.gnome.desktop.interface gtk-theme
> 'Grubvox-Dark-BL'
>  
> $ gsettings get org.gnome.desktop.interface icon-theme
> 'Tela-circle-nord'
> ```

The version @masakk1 uses is the previous version, in the new version I was playing a bit with the Gruvbox colour palette, so I changed the `Quick Settinigs` to a bluish colour, I see that my decision wasn't very wise xD

I'm going back to the old colour palette in the next update }:-]

**Comment by t3dium** [comment]
how well does the theme work on gnome 44? wondering whether i should update

**Comment by Kostrol** [comment]
Great themes overall, but having an issue with Gnome Software in particular, the corners refuse to round with the dark Gruvbox Borderless-Legacy Button Windows theme. I've used Tweaks to set the shell theme to BL-GS for the shell, and BL-LB for Legacy Applications, then copied the gtk-4.0 files to .config as specified.

https://i.imgur.com/lO1bJvE.png
