### ISSUE TITLE
Missing checkboxes in settings app (libadwaita)

### ISSUE THREAD

**Issue by n3thshan** [Fausto-Korpsvart/Gruvbox-GTK-Theme#4]
Steps to produce issue: 
Try clicking the gear icon next to Network Proxy in Network section of the Settings app and observe the check boxes in front of the proxy modes. I only noticed this in the settings app. Other gtk 4 apps like gnome-text-editor has a similar issue where the blank check-boxes appear but there's no indication of the selected check boxes.

**Comment by Fausto-Korpsvart** [comment]
> 

HI, @n3thshan, I hope to update tomorrow the Gruvbox Dark themes, I'm still working on fixing some issues and adapting the theme for Gnome 42 to work as good as possible in GTK4, thanks for reporting };-]
