### ISSUE TITLE
Hi, where have the light themes gone???

### ISSUE THREAD

**Issue by tomhoughton** [Fausto-Korpsvart/Gruvbox-GTK-Theme#42]

**Comment by Fausto-Korpsvart** [comment]
> _No description provided._

Sorry, I deleted it because it was not updated to Gnome 44 and had many bugs, but soon I will update it and upload it again.
If you want it you can go to the commit before the last one and download it.

**Comment by TheDevtop** [comment]
Last commit with light theme: c7a852728717e60a41c2b2fbeac70d2b2269b86c
Putting it here in case anyone comes across.

**Comment by olivertzeng** [comment]
yes i really want the light theme!

**Comment by olivertzeng** [comment]
> > _No description provided._
> 
> Sorry, I deleted it because it was not updated to Gnome 44 and had many bugs, but soon I will update it and upload it again. If you want it you can go to the commit before the last one and download it.

waiting for you~

**Comment by anticlam** [comment]
Any updates?

**Comment by olivertzeng** [comment]
> Sorry for the delay.
> 
> 
> 
> Thanks for the patience, because of the work I've been making slow progress with this GTK themes project but, although slow, I've made progress.
> 
> 
> 
> Soon I will make updates in some themes and then I will update little by little all the themes.
> 
> 
> 
> Thanks for the support and interest in the project, and I'm sorry it's taking so long, but there will be updates soon.

Go go you can do it!

**Comment by olivertzeng** [comment]
> Sorry for the delay.
> 
> Thanks for the patience, because of the work I've been making slow progress with this GTK themes project but, although slow, I've made progress.
> 
> Soon I will make updates in some themes and then I will update little by little all the themes.
> 
> Thanks for the support and interest in the project, and I'm sorry it's taking so long, but there will be updates soon.

did it succeed
