### ISSUE TITLE
Invalid name of pseudo-class

### ISSUE THREAD

**Issue by eeeXun** [Fausto-Korpsvart/Gruvbox-GTK-Theme#43]
`(blueman-applet:615): Gtk-WARNING **: 01:42:16.459: Theme parsing error: gtk.css:6691:68: Invalid name of pseudo-class`

I'm using `Gruvbox-Dark-BL`

**Comment by knedl1k** [comment]
Same error with Firefox 
`(firefox:81657): Gtk-WARNING **: 00:22:21.183: Theme parsing error: gtk.css:6703:68: Invalid name of pseudo-class`

I use Gruvbox-Dark-B

**Comment by choopsit** [comment]
Hi
I use Gruvbox-Dark-BL and got the same with xfce4-terminal, tilix and terminator, even when just used to feed a variable called with argument --version

screenshots in xfce4-terminal:
![gtk-warning](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/36983348/c86dd29c-ddf8-4c46-af4a-4509c153c72f)
![gtk-warning_in_script](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/36983348/cbdd81bf-f757-47a3-82ca-ba5f7c289dba)

**Comment by choopsit** [comment]
Commenting lines 6689 to 6701 of Gruvbox-Dark-BL/gtk-3.0/gtk.css fixes the problem with no impact for me using XFCE


lines I commented (the problem seems to be by there):

> .path-bar-box
>   .linked.nautilus-path-bar
>   button:not(.suggested-action):not(.destructive-action):last-child:dir(
>     ltr
>   ):disabled,
> .path-bar-box
>   .linked.nautilus-path-bar
>   button:not(.suggested-action):not(.destructive-action):first-child:dir(
>     rtl
>   ):disabled {
>   color: #89b482;
>   background-color: #282828;
> }
