### ISSUE TITLE
Applications' symbolic icon doesn't get colored in top bar

### ISSUE THREAD

**Issue by stpnwf** [Fausto-Korpsvart/Gruvbox-GTK-Theme#47]
![Screenshot from 2023-05-28 15-47-04](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/81482539/c624b2e1-5bb2-4d3b-9c08-e1b67d0770e3)

I am on Fedora 38

**Comment by eeeXun** [comment]
I have the same issue after 9d7e7c690724fb377c220632cd790a4b4be921b6. Roll back to c7a852728717e60a41c2b2fbeac70d2b2269b86c

**Comment by Fausto-Korpsvart** [comment]
This week I will try to dedicate time to this project to fix problems and upload the remaining issues that I haven't updated yet, sorry for the delay.

**Comment by eeeXun** [comment]
Hi @Fausto-Korpsvart , thanks you for maintaining. I find you updated a few days ago. But the top bar still hos no color.

![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/58657914/8b7aaaf7-b7fa-4563-b2bc-decfb43f2728)

Desktop Environment: mate

**Comment by Fausto-Korpsvart** [comment]
> Hi @Fausto-Korpsvart , thanks you for maintaining. I find you updated a few days ago. But the top bar still has no color.
> 
> ![image](https://private-user-images.githubusercontent.com/58657914/337953372-8b7aaaf7-b7fa-4563-b2bc-decfb43f2728.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzA5OTUsIm5iZiI6MTcxODAzMDY5NSwicGF0aCI6Ii81ODY1NzkxNC8zMzc5NTMzNzItOGI3YWFhZjctYjdmYS00NTYzLWIyYmMtZGVjZmI0M2YyNzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE0NDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjODI1MGRmYWVjZjQyZTU5YjA2ZTkwN2NhMDQ3YTA2MWQxNTU4OTY3YzYwODJlZmQ3ZjJkNDQ0ODlmMWZjNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gIUxXCnHElEsdaJq9KnP8NmOxWxLRALQQbhHcDMgIgI)
> 
> Desktop Environment: mate

Hello, @eeeXun, I think this depends more on the icon package than the theme itself, but I'll check to see if I can do it from the theme.
