### ISSUE TITLE
Button background looks odd in gtk2

### ISSUE THREAD

**Issue by hieulw** [Fausto-Korpsvart/Gruvbox-GTK-Theme#48]
I use gtk2 for qt applications `QT_QPA_PLATFORMTHEME=gtk2` so all qt application look like this in the `master`

![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/13571960/412b5bf4-6bb9-44c3-9cff-6953746f235d)

I fix it by temporary checkout https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/commit/c7a852728717e60a41c2b2fbeac70d2b2269b86c then it looks to be expected

![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/13571960/6a8ad08c-bf67-4b69-b032-615c5fe39aac)

**Comment by Fausto-Korpsvart** [comment]
> I use gtk2 for qt applications `QT_QPA_PLATFORMTHEME=gtk2` so all qt application look like this in the `master`
> 
> ![image](https://user-images.githubusercontent.com/13571960/245723494-412b5bf4-6bb9-44c3-9cff-6953746f235d.png)
> 
> I fix it by temporary checkout [c7a8527](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/commit/c7a852728717e60a41c2b2fbeac70d2b2269b86c) then it looks to be expected
> 
> ![image](https://user-images.githubusercontent.com/13571960/245725020-6a8ad08c-bf67-4b69-b032-615c5fe39aac.png)

Thanks for reporting, and sorry for the delay, too much work.

This week I will dedicate some time to this project and I will check every problem you have reported and update as soon as possible.

**Comment by hamzashahid-blit** [comment]
Any update?

**Comment by yancelawang** [comment]
Does it related? I also have same issue in GIMP.


![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/36460186/70d44a2f-da87-4094-8fd8-5aed6968c706)

**Comment by Fausto-Korpsvart** [comment]
> Does it related? I also have same issue in GIMP.
> 
> ![image](https://user-images.githubusercontent.com/36460186/267186109-70d44a2f-da87-4094-8fd8-5aed6968c706.png)

Greetings.

If you haven't changed the theme inside GIMP, then it is related to theme problems in GTK2, but as soon as possible I will make updates.

**Comment by yancelawang** [comment]
Hello again. I'm sorry, i didn't mean to rush you. But is there any update on this fix?

**Comment by hieulw** [comment]
> Hello again. I'm sorry, i didn't mean to rush you. But is there any update on this fix? 
> 
> 

based on commit history of this project just checkout commit like thread say and you'll fine.

**Comment by yancelawang** [comment]
> > Hello again. I'm sorry, i didn't mean to rush you. But is there any update on this fix?
> 
> based on commit history of this project just checkout commit like thread say and you'll fine.

I already do that but no changes.

![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/36460186/4da96838-d0d3-48af-bfa7-02052929f6a1)

**Comment by yancelawang** [comment]
Please ignore my previous comment. it turns out that I changed the theme on the gimp to dark. I change to System it fix for button text. But it show issue for combo box backround.

![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/36460186/dd99e922-d542-4f36-95fd-d1f76c353866)
