### ISSUE TITLE
[Bug] Icon alignment of the title bar is not properly aligned with the icon of the chrome based web apps (Progressive Web Apps)

### ISSUE THREAD

**Issue by isayakmondal** [Fausto-Korpsvart/Gruvbox-GTK-Theme#49]
![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/51121313/8138251d-848e-4123-9ec7-8b9e6116744f)
As it is visible from the screenshot the Icons are way too big compared to the standard icon size in the background in the title bar for the browser, also it's misaligned with the logo of the PWA. I've tried with many PWAs (YouTube Music, Gmail, WhatsApp) the exact misalignment in all of them.

My system details:
```
OS: Ubuntu 22.04.3 LTS x86_64
Kernel: 6.2.0-32-generic 
DE: GNOME 42.9
WM: Mutter
Theme: Gruvbox-Dark-BL [GTK2/3]
Scaling Factor: 1.25
```

**Comment by Fausto-Korpsvart** [comment]
> ![image](https://user-images.githubusercontent.com/51121313/266284989-8138251d-848e-4123-9ec7-8b9e6116744f.png) As it is visible from the screenshot the Icons are way too big compared to the standard icon size in the background in the title bar for the browser, also it's misaligned with the logo of the PWA. I've tried with many PWAs (YouTube Music, Gmail, WhatsApp) the exact misalignment in all of them.
> 
> My system details:
> 
> ```
> OS: Ubuntu 22.04.3 LTS x86_64
> Kernel: 6.2.0-32-generic 
> DE: GNOME 42.9
> WM: Mutter
> Theme: Gruvbox-Dark-BL [GTK2/3]
> Scaling Factor: 1.25
> ```

Thanks for reporting, I'm working on the new update, I know it's taking a while, because of my work I can't dedicate much time to GTK themes, but soon there will be updates.
