### ISSUE TITLE
New versions of some gnome (45) apps have wierd white backgrounds

### ISSUE THREAD

**Issue by AbrA-K** [Fausto-Korpsvart/Gruvbox-GTK-Theme#52]
Namely nautilus and the calendar app have this problem:
![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/127196460/710b11e3-6484-4732-9bb1-7cddcf471a0b)
![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/127196460/fc7b9540-2d16-4e69-83ad-8f77d5943e3e)

On first sight this doesn't seem super trivial to fix.
I'll poke around and look what I can do.

**Comment by darkshitllord** [comment]
did you by any chance find the cause of this and the solution? I'm also having the same problem with the gruvbox theme

**Comment by AbrA-K** [comment]
nope - I'm sadly not a GTK wizzard haha.
I took a glance in the gtk debugger if there was a class that I could theme differently, but (again, on first glance) there doesn't seem to be one.
Tools like Gradience have (or had idk) [this problem](https://github.com/GradienceTeam/Gradience/issues/828) as well i think, but there is stuff being done to fix it - I'll take a look at it

**Comment by darkshitllord** [comment]
Thanks for the reply 🙂, if i manage to fix it ill send the info here.

**Comment by darkshitllord** [comment]
just checked the css, changing the background color of .navigation-sidebar in gtk.css seems to work, at least for nautilus.

**Comment by AbrA-K** [comment]
admittedly I don't use this theme anymore, but are you sure that's enough? If I paint this part black it doesn't get everything (look at the top left):
![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/127196460/41a11810-33c6-442e-94ac-4cc05867e1a6)

honestly it looks fine if you have dark mode enabled - in this screenshot I have light mode enabled AND I have to unfocus the application to make it look weird. The quick fix is to enable dark mode to make the theme look fine.

**Comment by darkshitllord** [comment]
yeah i didn't even notice the color changes when you unfocus the window, but i guess it's not that big of a deal when having dark mode on fixes it.

**Comment by ducviet00** [comment]
I think it's related to https://github.com/vinceliuice/Graphite-gtk-theme/commit/2ca68704eaddca0554d8087f612fefef66e9de8e

**Comment by Fausto-Korpsvart** [comment]
Sorry for the delay.
You can test the Tokyonight theme, to see if everything is working fine, you can also report any bugs, testing this theme is just for you to check how the theme is working because it will be the same for Gruvbox, which I'm currently working on to update as soon as possible, sorry it's taking so long to update.

[Tokyonight-Testing](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/files/13716874/Tokyonight-Testing.zip)

**Comment by raherin** [comment]
I can confirm that the Tokyonight theme works for me on GTK4.0
