### ISSUE TITLE
GNOME 45 Top-Bar Dropdown Not Themed

### ISSUE THREAD

**Issue by alichtman** [Fausto-Korpsvart/Gruvbox-GTK-Theme#53]
Most of my system looks like this: 
![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/20600565/5cb974e9-8b5e-438a-9023-1f536983bb36)

But the top-bar dropdown is still using the Yaru theme from Ubuntu

![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/20600565/bd9da13e-42f0-4110-b131-deaf15caf899)

Any ideas about what's going on here?

```
$ gnome-shell --version
GNOME Shell 45.0
```

**Comment by XJ-0461** [comment]
In Gnome Tweaks, have you selected the Gruvbox theme for both 'Shell' as well as 'Legacy Applications'?
![tweaks-sc](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/32183393/f7c5ac53-5735-44bd-8cdd-cbb718dca6fe)
Seems like something that could be easily overlooked.
