### ISSUE TITLE
gtk 4 not themed properly

### ISSUE THREAD

**Issue by Ankur97444** [Fausto-Korpsvart/Gruvbox-GTK-Theme#59]
![2024-03-07T00:29:31,089013731+05:30](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/76205295/3569db52-07ce-4eea-b961-ffe6a2954b72)

**Comment by Usmani391** [comment]
![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/114348374/e907caaf-9154-4b03-add2-6ac897e9b276)
 
 Same issue
