### ISSUE TITLE
Borders "overflow"

### ISSUE THREAD

**Issue by Velho-P** [Fausto-Korpsvart/Gruvbox-GTK-Theme#60]
Some apps like Lutris, GreenWithEnvy and Easy Effects have this issue: 

![boderoverflow](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/159920579/918b1e34-b101-43b2-a9c1-01b67b9fe1b0)

Borders go outside my screen and overlaps my panel

Does anyone know how to fix it?

XFCE 4.18
Gruvbox-Dark-B

Thank you

**Comment by Fausto-Korpsvart** [comment]
> Some apps like Lutris, GreenWithEnvy and Easy Effects have this issue:
> 
> ![boderoverflow](https://private-user-images.githubusercontent.com/159920579/312880490-918b1e34-b101-43b2-a9c1-01b67b9fe1b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0OTcxNDQsIm5iZiI6MTcxODQ5Njg0NCwicGF0aCI6Ii8xNTk5MjA1NzkvMzEyODgwNDkwLTkxOGIxZTM0LWIxMDEtNDNiMi1hOWMxLTAxYjY3YjlmZTFiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwMDE0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjI4NjJiM2MwMjM0ODdmYzJkY2M0Y2I4ZmQzZGFlNDliNDQ3MDcxZTM3MjZjNTFkZTVlYWRhNTY1NDcwNWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VkZ7nAKaRyNnyOPK4LmSD21Nqpad1ozsyEitZNPhADM)
> 
> Borders go outside my screen and overlaps my panel
> 
> Does anyone know how to fix it?
> 
> XFCE 4.18 Gruvbox-Dark-B
> 
> Thank you

Hello, @Velho-P, Try the new version and let me know if the bug is fixed.
