### ISSUE TITLE
Some menu selection themeing issues introduced with new Gnome 46

### ISSUE THREAD

**Issue by Kostrol** [Fausto-Korpsvart/Gruvbox-GTK-Theme#61]
Would there be any quick easy fix within the css for this? Would be very happy if somebody could help, nothing else seems to have changed or broken besides this, or at least that I mind. Shell theme is Gruvbox-LB-GS.

Happens in Nautilus , settings and certain applications.

![2024-03-30_16-51](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/38816613/74a51977-6971-4d3f-ba42-d66dbacad504)

**Comment by Fausto-Korpsvart** [comment]
> Would there be any quick easy fix within the css for this? Would be very happy if somebody could help, nothing else seems to have changed or broken besides this, or at least that I mind. Shell theme is Gruvbox-LB-GS.
> 
> Happens in Nautilus , settings and certain applications.
> 
> ![2024-03-30_16-51](https://private-user-images.githubusercontent.com/38816613/318208470-74a51977-6971-4d3f-ba42-d66dbacad504.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzkwNjAsIm5iZiI6MTcxMTk3ODc2MCwicGF0aCI6Ii8zODgxNjYxMy8zMTgyMDg0NzAtNzRhNTE5NzctNjk3MS00ZDNmLWJhNDItZDY2ZGJhY2FkNTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEzMzkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOWM0NDQxMmY1MmIyNzI1NGFlYjQ3N2VkNTIzMmZkY2U1N2NmYjY3MmZjOTcxZTdjNzZiMmI2MDgzZjY0NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nOctt4gTgqjNkiD_pS4oPtjw3BubWiC39E1fWjwQWdQ)

Hello, @Kostrol.
Could you try the Tokyonight theme?
This theme has not been updated yet, I would like you to try the Tokyonight theme to see if it works, so I can fix the problems in Gruvbox before updating.

**Comment by Kostrol** [comment]
@Fausto-Korpsvart 

Beautiful, thank you for working on an update. So far this is looking excellent. 

It's so refreshing to finally see all the elements working, looking forward to see how the Gruvbox version will turn out. My only request is to keep the shell UI elements round instead of squared like they are in the current version. :)

![Screenshot from 2024-04-01 17-08-57](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/38816613/7cfef77a-16a2-44f0-8258-9557c906a976) ![Screenshot from 2024-04-01 17-33-29](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/38816613/5c35a49b-1c46-4943-b492-b79f12504334)


I did find some minor issues if I can point them out.

It has this beautiful little animation highlight indicator of when you have hit the top of the page when scrolling like the following image. However there is an issue with programs like gnome-extensions where if you scroll down this will create a static white line here like shown below.

![2024-04-01_16-46](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/38816613/302c8439-42d4-4aed-b2ec-45c0c5895539) ![2024-04-01_16-47](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/38816613/b40b497a-0c5f-45d1-ac85-8d0fd328a75f)


I also would love if this outlined/contrasted top border of the title window would be removed and instead kept uniform with the bottom border and corners. Sticks out when floating windows are stacked.

![2024-04-01_16-53](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/38816613/f4a10077-20c1-418c-962b-10bee5a13b13) ![2024-04-01_16-51](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/38816613/48cbd8c0-1260-44d2-9a0b-b1604e90a9e0)

Some flickering happening here as well.

https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/38816613/008915cd-e608-483f-a999-9d8b4a781a58

**Comment by Kostrol** [comment]
https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/38816613/32e4c640-3276-4f1f-8334-36c543c08881

**Comment by Fausto-Korpsvart** [comment]
@Kostrol, I will check the things you pointed out, this theme is not yet adapted for Gnome 46, remember that Gnome 46 is still in Beta, and it will be a little while before it is released with stable changes, so I will work to fix the things needed to make the theme work properly.

Thanks for your support.

**Comment by Fausto-Korpsvart** [comment]
Gruvbox theme updated, finally xD
I hope you try it and enjoy it, I also look forward to your bug reports.

Thanks for your support and patience.

**Comment by Kostrol** [comment]
Thank you very much for pushing the update @Fausto and your work, been enjoying the new look for a few days especially with the updated UI, though do have some difficulty adjusting to the new cyan-ish accent color. It's a big change from the previous version which I tend to prefer. I haven't dabbled much into CSS so I don't know how easy it would be to adjust to personal taste, i went over the 

Other than that a very good first impression and I'm happy it landed, believe it was a big undertaking.

What issues I could tell, was still present from my previous report with the Tokyonight shell was the flickering of the buttons that I can report so far:

> Screencast.from.2024-04-01.18-11-30.mp4

Not sure what goes on there.

**Comment by Fausto-Korpsvart** [comment]
> Thank you very much for pushing the update @Fausto and your work, been enjoying the new look for a few days especially with the updated UI, though do have some difficulty adjusting to the new cyan-ish accent color. It's a big change from the previous version which I tend to prefer. I haven't dabbled much into CSS so I don't know how easy it would be to adjust to personal taste
> 
> Other than that a very good first impression and I'm happy it landed, believe it was a big undertaking.
> 
> What issues I could tell, was still present from my previous report with the Tokyonight shell was the flickering of the buttons that I can report so far:
> 
> > Screencast.from.2024-04-01.18-11-30.mp4
> 
> Not sure what goes on there.

Greetings, @Kostrol, it's nice to know that the effort is worthwhile.

With the customisation issue, in the README you can see that when installing the theme from the terminal, you can pass certain parameters to change colours, for example, if you want a different accent colour you can do it this way: `./install.sh -t yellow`, there are several colours that can be used to change the tone of the accent, it's all in the README in the installation part.

Regarding the flickering on certain buttons, I have not yet identified where it comes from, I thought it was because I made some changes, but the theme I have based it on also has the same problem, I am still checking what can cause this error, once I identify it I will update, as it is a bit annoying flickering.

Thanks for your support.

**Comment by Kostrol** [comment]
Thank you for clarifying, I missed this in the README.

There seems to be some breakage in the installer for the yellow-dark theme.

Gruvbox-Yellow-Dark installs to ~/themes but it is missing important files gtk-4.0 folder, gtk-3.0 gtk.css files thumbnail: cp: cannot stat '/home/user/Gruvbox-GTK-Theme/themes/src/assets/gtk/thumbnails/thumbnail-Yellow-Dark.png': No such file or directory

```
 ./install.sh -c dark -t yellow -s standard  
``` 
Also only installs "Gruvbox-Yellow".
```
[ Wed Jun 12 18:58:02 ~/Gruvbox-GTK-Theme/themes ] λ ./install.sh -t yellow -c dark

GNOME Shell 46.2
Installing '/home/user/.themes/Gruvbox-Yellow'...
```
./install.sh -t yellow -c light seems to install the opposite but still with missing files.

```
Wed Jun 12 18:58:55 ~/Gruvbox-GTK-Theme/themes λ ./install.sh -t yellow -c light

GNOME Shell 46.2
Installing '/home/user/.themes/Gruvbox-Yellow-Dark'...

**Comment by Fausto-Korpsvart** [comment]
> Thank you for clarifying, I missed this in the README.
> 
> There seems to be some breakage in the installer for the yellow-dark theme.
> 
> Gruvbox-Yellow-Dark installs to ~/themes but it is missing important files gtk-4.0 folder, gtk-3.0 gtk.css files thumbnail: cp: cannot stat '/home/user/Gruvbox-GTK-Theme/themes/src/assets/gtk/thumbnails/thumbnail-Yellow-Dark.png': No such file or directory.
> 
> EDIT: I found correcting the small typo with the the case sensitivity for the path error, causing the missing files not to get installed, I've fixed it on my end by renaming the thumbnail from "thumbnail-Yellow-dark.png".
> 
> ```
> [ Wed Jun 12 18:58:59 ~/Gruvbox-GTK-Theme/themes ] λ ./install.sh -t yellow
> 
> GNOME Shell 46.2
> Installing '/home/user/.themes/Gruvbox-Yellow-Light'...
> Installing '/home/user/.themes/Gruvbox-Yellow-Dark'...
> cp: cannot stat '/home/user/Gruvbox-GTK-Theme/themes/src/assets/gtk/thumbnails/thumbnail-Yellow-Dark.png': No such file or directory
> ```
> 
> ```
>  ./install.sh -c dark -t yellow -s standard  
> ```
> 
> Also only installs "Gruvbox-Yellow".
> 
> ```
> [ Wed Jun 12 18:58:02 ~/Gruvbox-GTK-Theme/themes ] λ ./install.sh -t yellow -c dark
> 
> GNOME Shell 46.2
> Installing '/home/user/.themes/Gruvbox-Yellow'...
> ```
> 
> ./install.sh -t yellow -c light seems to install the opposite but still with missing files.
> 
> ```
> Wed Jun 12 18:58:55 ~/Gruvbox-GTK-Theme/themes λ ./install.sh -t yellow -c light
> 
> GNOME Shell 46.2
> Installing '/home/user/.themes/Gruvbox-Yellow-Dark'...
> ```

@Kostrol, are you using the latest update of the repo?

Because, talking about the assets problem, I have already updated all the assets verifying that everything is correctly in place, in fact, when I install the theme with the command `./install.sh -t yellow` I don't get any error.

Regarding the `./install.sh -t yellow -c light` command, you are right, I will check and fix it as soon as possible, I think it may be because I removed the `standard` theme version, because in this theme it is exactly the same as the light theme, in other themes from the same creator, the `standard` theme is a combination of the `Dark` and `Light` themes, but in this theme I have based, `Magnetic`, the `Standard` and `Light` themes are the same theme, so I decided to remove the `standard` version.
So I will check to fix this little bug.

Thanks for the report and your support.

**Comment by Kostrol** [comment]
On Wed, Jun 12, 2024 at 20:46 @korpsvart ***@***.***> wrote:

>
> @Kostrol <https://github.com/Kostrol>, are you using the latest update of
> the repo?
>
> Because, talking about the assets problem, I have already updated all the
> assets verifying that everything is correctly in place, in fact, when I
> install the theme with the command ./install.sh -t yellow I don't get any
> error.
>
> Cloned the repo and ran the installer around the time posted, so that’s
strange if it cant be replicated. I tried running the build script too at
one point just to test. Just wanted to report, solved by just renaming the
thumbnail file of the error and installed with the right assets and
everything. It was looking for «thumbnail-Yellow-Dark but the thumbnail was
in fact called «thumbnail-Yellow-dark», it was the same in the repo files
when i checked.

**Comment by Fausto-Korpsvart** [comment]
> On Wed, Jun 12, 2024 at 20:46 @korpsvart ***@***.***> wrote: @Kostrol <https://github.com/Kostrol>, are you using the latest update of the repo? Because, talking about the assets problem, I have already updated all the assets verifying that everything is correctly in place, in fact, when I install the theme with the command ./install.sh -t yellow I don't get any error. Cloned the repo and ran the installer around the time posted, so that’s
> strange if it cant be replicated. I tried running the build script too at one point just to test. Just wanted to report, solved by just renaming the thumbnail file of the error and installed with the right assets and everything. It was looking for «thumbnail-Yellow-Dark but the thumbnail was in fact called «thumbnail-Yellow-dark», it was the same in the repo files when i checked.

@Kostrol, you're right, sorry, I fixed it in Everforest and forgot to add the change to Gruvbox, when I update it will be solved, thanks.

Regarding installing the Light and Dark versions separately, I've already fixed it, I'll update as soon as I finish the Catppuccin theme.

Again, thanks for the report and your support }:]

**Comment by Fausto-Korpsvart** [comment]
> flickering

@Kostrol, Fixed bugs in buttons and switches, hover causes strange flickering.
