### ISSUE TITLE
Text Editor themes cannot be installed on Gedit 46.1 and 46.2

### ISSUE THREAD

**Issue by SpreadiesInSpace** [Fausto-Korpsvart/Gruvbox-GTK-Theme#62]
![Screenshot from 2024-04-16 01-27-43](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/106583914/11879be5-867a-4c95-a3b1-d3ca85fce5f0)
![Screenshot from 2024-04-16 01-28-12](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/106583914/83f7149a-e7c8-477a-aa4b-44eb97d374a6)

running gedit via commandline yields this:

(gedit:7111): libgedit-gtksourceview-WARNING **: 02:03:10.322: Failed to load style scheme file '/home/f16poom/.local/share/gedit/styles': Error on line 4 char 1: element 'style-scheme' requires attribute 'kind'

This baffles me since the theme is just 1 year old, and it has worked on Gedit 44 and 45.

**Comment by Fausto-Korpsvart** [comment]
> ![Screenshot from 2024-04-16 01-27-43](https://private-user-images.githubusercontent.com/106583914/322598212-11879be5-867a-4c95-a3b1-d3ca85fce5f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjMyMzEsIm5iZiI6MTcxMzM2MjkzMSwicGF0aCI6Ii8xMDY1ODM5MTQvMzIyNTk4MjEyLTExODc5YmU1LTg2N2EtNGM5NS1hM2IxLWQzY2E4NWZjZTVmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNDA4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjRjY2U4Y2RlMjc1N2Y5NDMyZmViZTY5ZWNjNGY2ZGU3Y2FkZDI5NjI2NDNjYjkzYjdmNDZmNjQyZjVlOGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PKUHkC_N8F8MJ61eA-tYt5FMZE9vJ1479FL5-MeaW9I) ![Screenshot from 2024-04-16 01-28-12](https://private-user-images.githubusercontent.com/106583914/322598227-83f7149a-e7c8-477a-aa4b-44eb97d374a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjMyMzEsIm5iZiI6MTcxMzM2MjkzMSwicGF0aCI6Ii8xMDY1ODM5MTQvMzIyNTk4MjI3LTgzZjcxNDlhLWU3YzgtNDc3YS1hYTRiLTQ0ZWI5N2QzNzRhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNDA4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTEyZDU5OGUxODNhOTY3OTIzYWY1ZTkyZTljYzgyYWQ3NmQwNTBhZDI0MmE2ZDJlN2U2NTY4ODIzYjQwZGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UyfHVK4i7xnPJxV4eBJH4yvlJnDIrkEbbaHwCcqTQIo)
> 
> running gedit via commandline yields this:
> 
> (gedit:7111): libgedit-gtksourceview-WARNING **: 02:03:10.322: Failed to load style scheme file '/home/f16poom/.local/share/gedit/styles': Error on line 4 char 1: element 'style-scheme' requires attribute 'kind'
> 
> This baffles me since the theme is just 1 year old, and it has worked on Gedit 44 and 45.

@SpreadiesInSpace, I will check again all the themes and then make an update.

Thank you for reporting.

**Comment by SpreadiesInSpace** [comment]
https://github.com/dracula/gedit/commit/2597c18eb61a6b4d2c57dc0f7a1866272e726183

I checked in with another gedit theme and this was the fix
