### ISSUE TITLE
Add sassc as needed package in the docs

### ISSUE THREAD

**Issue by n737xfx** [Fausto-Korpsvart/Gruvbox-GTK-Theme#66]
The documentation is saying that user should install gtk-engine-murrine and gnome-themes-extra before applying the theme. 

This might be correct if we don't choose manual installation. But you could add reminder for user who use manual approach to install sassc. I've seen that it need sassc in the build.sh file and it'll detect automatically if sassc isn't installed yet. It's fine, but adding them to the docs won't hurt i guess

Cheers, @Fausto-Korpsvart

**Comment by Fausto-Korpsvart** [comment]
> The documentation is saying that user should install gtk-engine-murrine and gnome-themes-extra before applying the theme.
> 
> This might be correct if we don't choose manual installation. But you could add reminder for user who use manual approach to install sassc. I've seen that it need sassc in the build.sh file and it'll detect automatically if sassc isn't installed yet. It's fine, but adding them to the docs won't hurt i guess
> 
> Cheers, @Fausto-Korpsvart

Hello, @n737xfx, you are right, I will do that, thanks for the suggestion.
