### ISSUE TITLE
Creating a new color for buttons, etc.

### ISSUE THREAD

**Issue by FarParticul** [Fausto-Korpsvart/Gruvbox-GTK-Theme#67]
### Description
Good afternoon, found your beautiful design theme, but ran into the fact that it only has colored highlights as the main blue color, the other colors didn't work for me and I had to redo the gtk-3.0 and gtk-4.0 configs a bit, but I don't remember which view I put since I have bspwn, I think it's Gruvbox-BL-Dark.

PS
--
![изображение](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/157636018/a3d54b6a-24f0-4b1a-9689-9b12ae3aace3)
 example of modified theme, but some parts remained and I understand it is color #408080, but there is no rgb or hex. 
 --
 If I understand what the color is, I can make a pull request for it.

**Comment by FarParticul** [comment]
I realized that the buttons were filled with color from the file thumbnail.png
but it's not so easy to change through the usual color-changing sites

**Comment by Fausto-Korpsvart** [comment]
> I realized that the buttons were filled with color from the file thumbnail.png but it's not so easy to change through the usual color-changing sites

Hi, @FarParticul, You can change the accent colour of the theme, actually, if you read the `README` in the `Installing Themes` section, you will see that it can be done easily, basically the command is: `./install.sh -t red`, for example, and that changes the default accent colour, which is blue, to red; in the same section you can see the colours that are available based on the Gruvbox colour palette.

**Comment by FarParticul** [comment]
> > I realized that the buttons were filled with color from the file thumbnail.png but it's not so easy to change through the usual color-changing sites
> 
> Hi, @FarParticul, You can change the accent colour of the theme, actually, if you read the `README` in the `Installing Themes` section, you will see that it can be done easily, basically the command is: `./install.sh -t red`, for example, and that changes the default accent colour, which is blue, to red; in the same section you can see the colours that are available based on the Gruvbox colour palette.

I know, but all these colors don't work for me, I'm just asking to make the color as foreground. Or I can try to figure it out myself and make the color in foreground.

The translator doesn't work for some reason, but I say, "that doesn't work for me."

**Comment by FarParticul** [comment]
It's kind of like these colors. And I remember that color was kind of the default in pling. But it became blue (I know you can change colors, but they are not for me, I mean I don't like them).
![изображение](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/157636018/542e0259-3788-41de-b166-0665e10c3af8)

**Comment by Fausto-Korpsvart** [comment]
> It's kind of like these colors. And I remember that color was kind of the default in pling. But it became blue (I know you can change colors, but they are not for me, I mean I don't like them). ![изображение](https://private-user-images.githubusercontent.com/157636018/340024299-542e0259-3788-41de-b166-0665e10c3af8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODI4NTMsIm5iZiI6MTcxODQ4MjU1MywicGF0aCI6Ii8xNTc2MzYwMTgvMzQwMDI0Mjk5LTU0MmUwMjU5LTM3ODgtNDFkZS1iMTY2LTA2NjVlMTBjM2FmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQyMDE1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWE2YWMxZjU1MDE4ODlmZjY2NDI5ZTcwOGYwODAwYzUwNjk3NjY5YTkwMDU3YzU5ZmE0MjY1MmVlN2Y5YTNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vDxkj5fO0XCUFavnNNpfGP06PTgM4OOOf-yZ3P5xZbs)

I'm sorry, but could you be a bit more specific? It would help to post some screenshots of the current theme and what you want me to modify, that would help me understand a bit better, because I don't quite understand what you mean.

**Comment by FarParticul** [comment]
> > It's kind of like these colors. And I remember that color was kind of the default in pling. But it became blue (I know you can change colors, but they are not for me, I mean I don't like them). ![изображение](https://private-user-images.githubusercontent.com/157636018/340024299-542e0259-3788-41de-b166-0665e10c3af8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODI4NTMsIm5iZiI6MTcxODQ4MjU1MywicGF0aCI6Ii8xNTc2MzYwMTgvMzQwMDI0Mjk5LTU0MmUwMjU5LTM3ODgtNDFkZS1iMTY2LTA2NjVlMTBjM2FmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQyMDE1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWE2YWMxZjU1MDE4ODlmZjY2NDI5ZTcwOGYwODAwYzUwNjk3NjY5YTkwMDU3YzU5ZmE0MjY1MmVlN2Y5YTNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vDxkj5fO0XCUFavnNNpfGP06PTgM4OOOf-yZ3P5xZbs)
> 
> I'm sorry, but could you be a bit more specific? It would help to post some screenshots of the current theme and what you want me to modify, that would help me understand a bit better, because I don't quite understand what you mean.

I'm trying to write specifically, but the translator doesn't translate the way I want it to.
I'll try to explain again, in your theme there is no foreground color(img1), that is, this/these colors, but I made a theme gtk3/gtk4(img2), but I can not make buttons on the picture thumbnail.png(img3), and as if I want to be the color that I showed in the picture, or as I have in the theme, that is, that it was also the main (if so you can).

PS - or if I get my hands on it, I don't mind making this color myself.

img1
![изображение](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/157636018/82f332e2-2146-4469-9b6d-f13276381634)

img2
![изображение](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/157636018/a9340332-2e46-43f6-a073-6a2063ff63c9)

img3 - This just shows that the color is applied through thumbnail.png.
![kkkkkddddd](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/157636018/94f5c1b1-ce6c-4110-bfec-92d64f81518f)

**Comment by FarParticul** [comment]
By the way, I was wondering how you create this file.
![thumbnail](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/157636018/a9c3f350-5c25-4fe0-9572-02ea33db191f)

**Comment by Fausto-Korpsvart** [comment]
> > > It's kind of like these colors. And I remember that color was kind of the default in pling. But it became blue (I know you can change colors, but they are not for me, I mean I don't like them). ![изображение](https://private-user-images.githubusercontent.com/157636018/340024299-542e0259-3788-41de-b166-0665e10c3af8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODI4NTMsIm5iZiI6MTcxODQ4MjU1MywicGF0aCI6Ii8xNTc2MzYwMTgvMzQwMDI0Mjk5LTU0MmUwMjU5LTM3ODgtNDFkZS1iMTY2LTA2NjVlMTBjM2FmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQyMDE1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWE2YWMxZjU1MDE4ODlmZjY2NDI5ZTcwOGYwODAwYzUwNjk3NjY5YTkwMDU3YzU5ZmE0MjY1MmVlN2Y5YTNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vDxkj5fO0XCUFavnNNpfGP06PTgM4OOOf-yZ3P5xZbs)
> > 
> > 
> > I'm sorry, but could you be a bit more specific? It would help to post some screenshots of the current theme and what you want me to modify, that would help me understand a bit better, because I don't quite understand what you mean.
> 
> I'm trying to write specifically, but the translator doesn't translate the way I want it to. I'll try to explain again, in your theme there is no foreground color(img1), that is, this/these colors, but I made a theme gtk3/gtk4(img2), but I can not make buttons on the picture thumbnail.png(img3), and as if I want to be the color that I showed in the picture, or as I have in the theme, that is, that it was also the main (if so you can).
> 
> PS - or if I get my hands on it, I don't mind making this color myself.
> 
> img1 ![изображение](https://private-user-images.githubusercontent.com/157636018/340028293-82f332e2-2146-4469-9b6d-f13276381634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODQ3MjIsIm5iZiI6MTcxODQ4NDQyMiwicGF0aCI6Ii8xNTc2MzYwMTgvMzQwMDI4MjkzLTgyZjMzMmUyLTIxNDYtNDQ2OS05YjZkLWYxMzI3NjM4MTYzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQyMDQ3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzYzYmQwYWMxYjg2MzM0OTIwNTRiMWRmNjRhYTJiZThiOWE5MjkyODVjOWFlZjI0YjRkYzJmZTM3ZmIwOWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SUCcjt0HPhSi3d280IV1At3y_zaGDVWsXgHLp7ZW8KQ)
> 
> img2 ![изображение](https://private-user-images.githubusercontent.com/157636018/340028314-a9340332-2e46-43f6-a073-6a2063ff63c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODQ3MjIsIm5iZiI6MTcxODQ4NDQyMiwicGF0aCI6Ii8xNTc2MzYwMTgvMzQwMDI4MzE0LWE5MzQwMzMyLTJlNDYtNDNmNi1hMDczLTZhMjA2M2ZmNjNjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQyMDQ3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYThlZjFmZWRhMDg5NGE3ZmNhZDE5MWM4Nzk0ZmM0MDE3YTU1Zjg3ZTE2ZTNiNDk1MjI2MmYyNmQ1MDk5YWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iMnLrsDgC1kaQAWtYWV9LtW53vyqhQa2Te8W38RRAq4)
> 
> img3 - This just shows that the color is applied through thumbnail.png. ![kkkkkddddd](https://private-user-images.githubusercontent.com/157636018/340028367-94f5c1b1-ce6c-4110-bfec-92d64f81518f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODQ3MjIsIm5iZiI6MTcxODQ4NDQyMiwicGF0aCI6Ii8xNTc2MzYwMTgvMzQwMDI4MzY3LTk0ZjVjMWIxLWNlNmMtNDExMC1iZmVjLTkyZDY0ZjgxNTE4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQyMDQ3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjE4OWJjYmI1MGEwMDE3ZGM4YjQ3M2JiNGRmNDA2MmY0YzUxMjM4YWYyZWUxNTAxOWFlMGYyOGZiOTg0YThlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SATrZ3SEAGfhxh4tyzfIglxLtLWlosCJNEO0TBc1sYc)

I'm sorry, I didn't understand, but I think I now understand a bit of what you mean.
What you're saying is that you want to change the blue colour of the buttons to a colour from the light colour palette, like the ones in the foreground, but these colours are not configured in the accent colour palette and that's why you can't change them, right?

Well, try this: go to `src/sass/_color-palette-default.scss` and change the value of the following lines:

```

63 | $default-light: $blue-light;
64 | $default-dark: $blue-dark;

63 | $default-light: $grey-450;
64 | $default-dark: $grey-200;

```
Then run the `./install.sh` command and let me know if it worked.

**Comment by FarParticul** [comment]
> > > > It's kind of like these colors. And I remember that color was kind of the default in pling. But it became blue (I know you can change colors, but they are not for me, I mean I don't like them). ![изображение](https://private-user-images.githubusercontent.com/157636018/340024299-542e0259-3788-41de-b166-0665e10c3af8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODI4NTMsIm5iZiI6MTcxODQ4MjU1MywicGF0aCI6Ii8xNTc2MzYwMTgvMzQwMDI0Mjk5LTU0MmUwMjU5LTM3ODgtNDFkZS1iMTY2LTA2NjVlMTBjM2FmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQyMDE1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWE2YWMxZjU1MDE4ODlmZjY2NDI5ZTcwOGYwODAwYzUwNjk3NjY5YTkwMDU3YzU5ZmE0MjY1MmVlN2Y5YTNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vDxkj5fO0XCUFavnNNpfGP06PTgM4OOOf-yZ3P5xZbs)
> > > 
> > > 
> > > I'm sorry, but could you be a bit more specific? It would help to post some screenshots of the current theme and what you want me to modify, that would help me understand a bit better, because I don't quite understand what you mean.
> > 
> > 
> > I'm trying to write specifically, but the translator doesn't translate the way I want it to. I'll try to explain again, in your theme there is no foreground color(img1), that is, this/these colors, but I made a theme gtk3/gtk4(img2), but I can not make buttons on the picture thumbnail.png(img3), and as if I want to be the color that I showed in the picture, or as I have in the theme, that is, that it was also the main (if so you can).
> > PS - or if I get my hands on it, I don't mind making this color myself.
> > img1 ![изображение](https://private-user-images.githubusercontent.com/157636018/340028293-82f332e2-2146-4469-9b6d-f13276381634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODQ3MjIsIm5iZiI6MTcxODQ4NDQyMiwicGF0aCI6Ii8xNTc2MzYwMTgvMzQwMDI4MjkzLTgyZjMzMmUyLTIxNDYtNDQ2OS05YjZkLWYxMzI3NjM4MTYzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQyMDQ3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzYzYmQwYWMxYjg2MzM0OTIwNTRiMWRmNjRhYTJiZThiOWE5MjkyODVjOWFlZjI0YjRkYzJmZTM3ZmIwOWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SUCcjt0HPhSi3d280IV1At3y_zaGDVWsXgHLp7ZW8KQ)
> > img2 ![изображение](https://private-user-images.githubusercontent.com/157636018/340028314-a9340332-2e46-43f6-a073-6a2063ff63c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODQ3MjIsIm5iZiI6MTcxODQ4NDQyMiwicGF0aCI6Ii8xNTc2MzYwMTgvMzQwMDI4MzE0LWE5MzQwMzMyLTJlNDYtNDNmNi1hMDczLTZhMjA2M2ZmNjNjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQyMDQ3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYThlZjFmZWRhMDg5NGE3ZmNhZDE5MWM4Nzk0ZmM0MDE3YTU1Zjg3ZTE2ZTNiNDk1MjI2MmYyNmQ1MDk5YWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iMnLrsDgC1kaQAWtYWV9LtW53vyqhQa2Te8W38RRAq4)
> > img3 - This just shows that the color is applied through thumbnail.png. ![kkkkkddddd](https://private-user-images.githubusercontent.com/157636018/340028367-94f5c1b1-ce6c-4110-bfec-92d64f81518f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODQ3MjIsIm5iZiI6MTcxODQ4NDQyMiwicGF0aCI6Ii8xNTc2MzYwMTgvMzQwMDI4MzY3LTk0ZjVjMWIxLWNlNmMtNDExMC1iZmVjLTkyZDY0ZjgxNTE4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQyMDQ3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjE4OWJjYmI1MGEwMDE3ZGM4YjQ3M2JiNGRmNDA2MmY0YzUxMjM4YWYyZWUxNTAxOWFlMGYyOGZiOTg0YThlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SATrZ3SEAGfhxh4tyzfIglxLtLWlosCJNEO0TBc1sYc)
> 
> I'm sorry, I didn't understand, but I think I now understand a bit of what you mean. What you're saying is that you want to change the blue colour of the buttons to a colour from the light colour palette, like the ones in the foreground, but these colours are not configured in the accent colour palette and that's why you can't change them, right?
> 
> Well, try this: go to `src/sass/_color-palette-default.scss` and change the value of the following lines:
> 
> ```
> 
> 63 | $default-light: $blue-light;
> 64 | $default-dark: $blue-dark;
> 
> 63 | $default-light: $grey-450;
> 64 | $default-dark: $grey-200;
> ```
> 
> Then run the `./install.sh` command and let me know if it worked.

Man, I didn't even know it was done here, I thought all topics were created at once, thanks a lot!
