### ISSUE TITLE
macOS Buttons doesn't work in mate DE

### ISSUE THREAD

**Issue by eeeXun** [Fausto-Korpsvart/Gruvbox-GTK-Theme#68]
Hi, there is a similar problem in #47. And I finally figure out that the problem only appears in mate. I tested it on cinnamon and xfce4, both of them work perfectly.

But I still don't know why it does't work on mate. If you need more information, I can help as best as I can.

p.s. The problem appears in commit after https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/commit/9d7e7c690724fb377c220632cd790a4b4be921b6. So I rollback to https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/commit/c7a852728717e60a41c2b2fbeac70d2b2269b86c.

**Comment by Fausto-Korpsvart** [comment]
> Hi, there is a similar problem in #47. And I finally figure out that the problem only appears in mate. I tested it on cinnamon and xfce4, both of them work perfectly.
> 
> But I still don't know why it does't work on mate. If you need more information, I can help as best as I can.
> 
> p.s. The problem appears in commit after [9d7e7c6](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/commit/9d7e7c690724fb377c220632cd790a4b4be921b6). So I rollback to [c7a8527](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/commit/c7a852728717e60a41c2b2fbeac70d2b2269b86c).

Hello, @eeeXun, could you add some screenshots to see a bit of what you mean?

Anyway, I will check and fix bugs and update as soon as possible.

Thanks for the report.

**Comment by eeeXun** [comment]
This is macOS Buttons under mate
![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/58657914/69f4ad14-10c0-484d-bbde-9585a98a27a4)

This is macOS Buttons under cinnamon
![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/58657914/38ca4be0-fae0-4510-a418-5a8cae942f04)

**Comment by eeeXun** [comment]
Hi, @Fausto-Korpsvart . I find out the problem is cause by wrong icons in `metacity-1`. Hope this can help.

**Comment by Fausto-Korpsvart** [comment]
> Hi, @Fausto-Korpsvart . I find out the problem is cause by wrong icons in `metacity-1`. Hope this can help.

Hi, @eeeXun, I'll check this out today, as I plan to update several themes tomorrow and it would be great to have this sorted out for the update.

Thanks for the tip and your support.

**Comment by Fausto-Korpsvart** [comment]
The problem is fixed.
Thanks again for the tip.
