### ISSUE TITLE
Missing rounded borders

### ISSUE THREAD

**Issue by mairacanal** [Fausto-Korpsvart/Gruvbox-GTK-Theme#7]
Looks like there is some kind of issue with the rounded borders, as can be seen below.

![image](https://user-images.githubusercontent.com/61601791/177366400-d079330f-d1f6-4b14-96e7-a112a99d8228.png)

### System
OS: Fedora 36
GNOME: Gnome 42.2

I installed the theme by copying the Gruvbox-Dark-BL folder to the `~/.themes/` folder and copying the gtk-Gruvbox-Dark-BL.css to the `~/.config/gtk-4.0/` folder.

There is something wrong with my installation?

**Comment by Fausto-Korpsvart** [comment]
> Looks like there is some kind of issue with the rounded borders, as can be seen below.
> 
> ![image](https://user-images.githubusercontent.com/61601791/177366400-d079330f-d1f6-4b14-96e7-a112a99d8228.png)
> 
> ### System
> OS: Fedora 36 GNOME: Gnome 42.2
> 
> I installed the theme by copying the Gruvbox-Dark-BL folder to the `~/.themes/` folder and copying the gtk-Gruvbox-Dark-BL.css to the `~/.config/gtk-4.0/` folder.
> 
> There is something wrong with my installation?

The border problem is now fixed, sorry it took so long.
Now you can try it and comment, if you find new problems };-]
