### ISSUE TITLE
Where to edit size of title bar and things?

### ISSUE THREAD

**Issue by hasukomusicvpn** [Fausto-Korpsvart/Gruvbox-GTK-Theme#71]
I tried finding in the file gtk-3.0 but i think i missed it or not found it

**Comment by Fausto-Korpsvart** [comment]
> I tried finding in the file gtk-3.0 but i think i missed it or not found it

If you look in the README you will see that you can pass the `-s compact` parameter to install a compact size version, try it and let me know if that is what you are looking for.
