### ISSUE TITLE
Option to make gnome panel also darker with the blackness tweak

### ISSUE THREAD

**Issue by ouyama-sa** [Fausto-Korpsvart/Gruvbox-GTK-Theme#72]
I really love the black version of the theme, but I think it would be better if it applied also to the menus and panel's palette. Just a suggestion, great theme.

**Comment by Fausto-Korpsvart** [comment]
> I really love the black version of the theme, but I think it would be better if it applied also to the menus and panel's palette. Just a suggestion, great theme.

I'm going to check how it would look like with those changes you suggest, but I think the problem would be the visibility of the menus, but I'll check and if I decide I'll make the change.

Thanks for the suggestion }:]
