### ISSUE TITLE
Can we have less borders?

### ISSUE THREAD

**Issue by dxps** [Fausto-Korpsvart/Gruvbox-GTK-Theme#8]
@Fausto-Korpsvart 

This is a great theme!

I am using the Graphite theme, but with minor customizations (such as stronger border for the active window).
So this is how it looks:
![image](https://user-images.githubusercontent.com/14140226/177569648-3bd5b4b9-ed92-4f34-807b-a8427e4b025b.png)

And with this GTK Theme (the _Dark BL_ flavor):
![image](https://user-images.githubusercontent.com/14140226/177577789-eccd22ce-2f80-4d25-9bf9-ebbaf645c39a.png)

and the _Dark B_ flavor:
![image](https://user-images.githubusercontent.com/14140226/177576324-a99f8c02-491a-4266-97cc-acabb46c555c.png)

Can you address this, please?

Thanks a lot!

Update: I see that _Gruvbox-Light_ version looks good, though. But I definitely prefer the Dark and borderless flavor.
![image](https://user-images.githubusercontent.com/14140226/177578303-cbe7c2bc-b80b-424d-bc75-251fd96ea47a.png)

**Comment by dxps** [comment]
At the same time I'd have to understand what to do with G42 (Gnome 42 specific, I guess) file,
which might actually be very relevant to my case (using Pop!_OS 22.04 LTS, GNOME 42.2).

**Comment by dxps** [comment]
Really appreciate the quick feedback @Fausto-Korpsvart ! :blush: 
And thanks for the details regarding Gnome 42 specific file. :pray: 

Meanwhile, I could also try to create another flavor from what I [currently have and use](https://github.com/dxps/Graphite-gtk-theme/blob/main/readme_dxps.md) (as a lighter nordic) to such gruvbox influence.

Speaking about theming knowledge:
- As you also mentioned [here](https://www.gnome-look.org/p/1681313), did you find any good references on how GTK theming can be done?
  I mean, besides the official [gtk3](https://docs.gtk.org/gtk3/css-overview.html) or [gtk4](https://docs.gtk.org/gtk4/css-overview.html) docs.
- I guess I shall also find some time to spend on this topic to satisfy my OCD.
  - Maybe this [GTK Theming Guide](https://github.com/surajmandalcell/Gtk-Theming-Guide/blob/master/creating_gtk_themes.md) would be handy enough.

I leave it up to you whether to have this ticket open as a reminder or close it.

**Comment by dxps** [comment]
Regarding suggestions, if I may :blush:  (things that I actually did on my customization of that Graphite nord flavor):
1. While I love how that nice edge border looks, it actually gets "interrupted" on the corners in certain windows like Firefox.
   ![image](https://user-images.githubusercontent.com/14140226/177624936-d3e07350-7af0-442c-adc9-8eb12e21023e.png)
   - This is the reason I didn't use that border, but strongly increase the shadow of the active window, so that it's pretty distinctive even on darker backgrounds. Like this (with GitHub Dark theme on the upper part of the background):
     ![image](https://user-images.githubusercontent.com/14140226/177625729-81b828ce-ca16-4b11-92da-9bba3ff0bc15.png)


2. The are people (myself included, ofc) that would rather prefer a less contrast (or less emphasized, or just some minimal symbols like `-`, `+`, `x` for the window icons).
   - These macOS influenced icons and their colors look like the most important things in the window.
   - For such audience, I guess a version to just have such different icons alternative would definitely help.

**Comment by Fausto-Korpsvart** [comment]
> Really appreciate the quick feedback @Fausto-Korpsvart ! blush And thanks for the details regarding Gnome 42 specific file. pray
> 
> Meanwhile, I could also try to create another flavor from what I [currently have and use](https://github.com/dxps/Graphite-gtk-theme/blob/main/readme_dxps.md) (as a lighter nordic) to such gruvbox influence.
> 
> Speaking about theming knowledge:
> 
> * As you also mentioned [here](https://www.gnome-look.org/p/1681313), did you find any good references on how GTK theming can be done?
>   I mean, besides the official [gtk3](https://docs.gtk.org/gtk3/css-overview.html) or [gtk4](https://docs.gtk.org/gtk4/css-overview.html) docs.
> * I guess I shall also find some time to spend on this topic to satisfy my OCD.
>   
>   * Maybe this [GTK Theming Guide](https://github.com/surajmandalcell/Gtk-Theming-Guide/blob/master/creating_gtk_themes.md) would be handy enough.
> 
> I leave it up to you whether to have this ticket open as a reminder or close it.

About theme documentation:

In fact, the links you have provided are the ones that helped me to start getting involved in GTK themes, there is very little documentation on how to get started, to review the documentation that already exists you must have some knowledge of CSS and study how GTK works, but outside all that documentation I have not found anything else.

The 'Widget Factory' and 'GTK Inspector' have also helped me a lot, but with the new changes that have been made thanks to 'libadwaita' I have to start reviewing all the documentation in more depth to understand the new theme creation operation.

**Comment by Fausto-Korpsvart** [comment]
> Regarding suggestions, if I may blush (things that I actually did on my customization of that Graphite nord flavor):
> 
> 1. While I love how that nice edge border looks, it actually gets "interrupted" on the corners in certain windows like Firefox.
>    ![image](https://user-images.githubusercontent.com/14140226/177624936-d3e07350-7af0-442c-adc9-8eb12e21023e.png)
>    
>    * This is the reason I didn't use that border, but strongly increase the shadow of the active window, so that it's pretty distinctive even on darker backgrounds. Like this (with GitHub Dark theme on the upper part of the background):
>      ![image](https://user-images.githubusercontent.com/14140226/177625729-81b828ce-ca16-4b11-92da-9bba3ff0bc15.png)
> 2. The are people (myself included, ofc) that would rather prefer a less contrast (or less emphasized, or just some minimal symbols like `-`, `+`, `x` for the window icons).
>    
>    * These macOS influenced icons and their colors look like the most important things in the window.
>    * For such audience, I guess a version to just have such different icons alternative would definitely help.

You are right, this looks horrible in Firefox and some applications, it is part of the problems in GTK3, and I have been looking for a solution to be able to continue with the styles of my themes and that Firefox is not affected, but unfortunately I have not found it yet the solution; I use Brave and for web development I rarely use Firefox, so it doesn't affect me too much, but most of the Linux community uses Firefox as their main browser, so I'm still looking for a solution, which might be easy, but it's not I have enough knowledge about creating themes to find that solution.

Regarding the shadows, yes, I've thought about making them a little more noticeable, especially in the borderless themes, but these are things that I have to test and play with a little to see what those changes look like, anyway , thanks for your suggestions I will take them into account when I do the tests and, if I like them, you will see the changes in the following updates.

Anyway, here's a test of the fixes for the next update:
![testing](https://user-images.githubusercontent.com/47998118/177653666-a892a05c-4655-4593-932e-f80999dccac3.png)

**Comment by dxps** [comment]
Sounds great, thanks!
Regarding borders differences GTK3/4, this [WhiteSur-Nord-Theme](https://www.gnome-look.org/p/1704248/) is a source of inspiration.

**Comment by dxps** [comment]
For now, inspired by this theme and Gruvbox colors, I ended up having this variant on my side and I'm pretty happy with it. :blush: 
The purpose is to see what others might expect from such a theme (although things are subjective and you can't make everybody happy all the times).
And now I see that I shall use the icon scheme that you have since it's consistent with the rest.

![image](https://user-images.githubusercontent.com/14140226/180818506-64bfb176-369a-4377-a61a-c8d6c0d9f0cf.png)

**Comment by Fausto-Korpsvart** [comment]
> For now, inspired by this theme and Gruvbox colors, I ended up having this variant on my side and I'm pretty happy with it. blush The purpose is to see what others might expect from such a theme (although things are subjective and you can't make everybody happy all the times). And now I see that I shall use the icon scheme that you have since it's consistent with the rest.
> 
> ![image](https://user-images.githubusercontent.com/14140226/180818506-64bfb176-369a-4377-a61a-c8d6c0d9f0cf.png)

Sorry for taking so long to respond, I've been quite busy.
It's great how you have achieved that minimalism, it looks really cool, and I think many may like it, minimalism is always great in desktop and working environments.

I really like this version a lot, very inspiring, I will see how to work on a third version that can be really borderless because your version looks great, I like that shadow work. I will try to make some time to work on that, or in my free time dedicate it to that new version, thanks for sharing your mod.

At the moment, I've already updated with the fixes for the tree view and the version with legacy buttons. };-]

**Comment by dxps** [comment]
No worries. Meanwhile, we got some very nice extension in the Gnome community: [Rounded Windows Corners](https://extensions.gnome.org/extension/5237/rounded-window-corners/).
I just tested and it's just lovely!

With minimal bordering (width of 1 and the same color as the window background) all the edges look great, and you can also control the shadow. I finally have everything - including the Terminal window - rounded. :man_dancing: 

![image](https://user-images.githubusercontent.com/14140226/182583668-6c8b43f0-5d5f-45ea-ac5b-d736ec0b73e2.png)

**Comment by Fausto-Korpsvart** [comment]
> No worries. Meanwhile, we got some very nice extension in the Gnome community: [Rounded Windows Corners](https://extensions.gnome.org/extension/5237/rounded-window-corners/). I just tested and it's just lovely!
> 
> With minimal bordering (width of 1 and the same color as the window background) all the edges look great, and you can also control the shadow. I finally have everything - including the Terminal window - rounded. man_dancing
> 
> ![image](https://user-images.githubusercontent.com/14140226/182583668-6c8b43f0-5d5f-45ea-ac5b-d736ec0b73e2.png)

You're right, finally, an extension that really helps with rounded corners, I'm going to try it out, thanks for the tip.

Your theme looks great, I really like that icon colour, it plays nicely with the Gruvbox Soft

Thanks for your support.

**Comment by augustobritodev** [comment]
wow, will be great if we have less border... 

at nautilus i found a little orange at selected folder (left side) its ok? or must be another color?

![Screenshot from 2022-08-15 08-52-27](https://user-images.githubusercontent.com/7965922/184631111-8c7211f1-b8f1-4aa2-80c2-25fdbeb285d8.png)

**Comment by Fausto-Korpsvart** [comment]
> wow, will be great if we have less border...
> 
> at nautilus i found a little orange at selected folder (left side) its ok? or must be another color?
> 
> ![Screenshot from 2022-08-15 08-52-27](https://user-images.githubusercontent.com/7965922/184631111-8c7211f1-b8f1-4aa2-80c2-25fdbeb285d8.png)
> 
> another question, is there a way to reduce de border size?
> 
> ![Screenshot from 2022-08-15 09-04-50](https://user-images.githubusercontent.com/7965922/184632107-c860b432-3a3a-4954-ad29-87275ebb9649.png)

@augustobritodev, yes, that's supposed to be the colour, it's to see the active directory in the sidebar, they also have the same colour, the title of the active tab and the active directory in the Files path bar.

[Here](https://www.pling.com/p/1681313/) are the variants of the theme, the `Gruvbox-Dark-BL` is the Borderless version, there is also `Gruvbox-Dark-BL-Legacy-Buttons` if you don't want the macOS-style window control buttons.

**Comment by t3dium** [comment]
yeah i personally use borderless for the gnome shell theme and with borders for apps, looks nice that way
