### ISSUE TITLE
Sorry for this issue

### ISSUE THREAD

**Issue by decipher3114** [Fausto-Korpsvart/Gruvbox-GTK-Theme#9]
Hello there is no issue. I just wanna ask how to keep bluetooth menu in top right quick settings even after turning off bluetooth.
Please tell SIR

**Comment by Fausto-Korpsvart** [comment]
> Hello there is no issue. I just wanna ask how to keep bluetooth menu in top right quick settings even after turning off bluetooth. Please tell SIR

You must search in Gnome Extension for the 'Bluetooth Quick Connect' extension.

**Comment by decipher3114** [comment]
I have already tried that sir but the bluetooth menu don't persist there. It disappear as soon as BT is turned off.

**Comment by Fausto-Korpsvart** [comment]
> I have already tried that sir but the bluetooth menu don't persist there. It disappear as soon as BT is turned off.

I don't know how to solve your problem, I just installed the extension and that was enough, I'm on Fedora 36.
